"use client";
import { useState } from "react";

const scenarios = {
  rain:["It’s raining","A beautiful way through Paris—mostly under cover.","Galerie Vivienne → Palais-Royal arcades → Véro-Dodat","64 min · 0.8 km · mostly sheltered"],
  heat:["It’s too hot","Cool interiors, short crossings, no wasted energy.","Salle Ovale → covered passages → quiet museum option","72 min · low effort · indoor-first"],
  ticket:["I have a ticket","Your reservation becomes the anchor of your day.","Flexible discovery → correct Louvre entrance → protected arrival","20 min safety margin · route contracts if needed"],
  secret:["Surprise me","The Paris most visitors walk straight past.","A rare gallery → overlooked courtyard → quiet reveal","58 min · no ticket · Velvet Pick"],
};

export default function Home(){
  const [scenario,setScenario]=useState<keyof typeof scenarios>("rain");
  const [openFaq,setOpenFaq]=useState(0);
  const [checkout,setCheckout]=useState(false);
  const selected=scenarios[scenario];
  const buy=()=>{setCheckout(true);setTimeout(()=>document.querySelector("#checkout")?.scrollIntoView({behavior:"smooth",block:"center"}),20)};
  const faqs=[
    ["When does my Pass start?","Only when you press “Activate now” and confirm. Buying or opening your link does not start the clock."],
    ["Do I need to download an app?","No. The launch version opens as a secure web app on your phone. You may add it to your home screen."],
    ["Are museum tickets included?","No. NOW can protect a ticket you own and help find booking options, but attraction tickets are purchased separately."],
    ["Is Paris Uncovered required?","Never. Paris NOW is complete on its own. Uncovered is an optional permanent premium guide."],
    ["What language is available?","The launch edition is in English. Additional languages and destinations are planned."],
  ];
  return <main>
    <header className="nav"><a className="wordmark nowWordmark" href="#top"><span className="rings"><i/><i/></span><span className="productBrand"><b><span>Paris</span><em>NOW</em></b></span></a><nav><a href="#how">How it works</a><a href="#features">Inside NOW</a><a href="#passes">Passes</a></nav><div className="navRight"><span className="navHouse"><small>BY</small><img src="/images/velvet-passport-logo.png" alt="Velvet Passport"/></span><a className="navCta" href="#passes">GET PARIS NOW</a></div></header>

    <section className="hero" id="top"><div className="heroCopy"><p className="kicker heroKicker"><b>WELCOME TO PARIS NOW</b><span>INTELLIGENT TRAVEL, IN THE MOMENT</span></p><h1>Paris, as it happens.<br/><em>Your plans, built for the moment.</em></h1><p className="lead">Paris NOW builds your next experience around where you are, how much time you have, the weather, your energy and the tickets you cannot afford to miss.</p><div className="actions"><a className="button gold" href="#passes">CHOOSE YOUR PASS <span>→</span></a><a className="textLink" href="#demo">See NOW decide ↓</a></div><div className="trust"><span>✓ Activate when you’re ready</span><span>✓ No app download</span><span>✓ One payment</span></div></div>
      <div className="product"><div className="halo"/><div className="phone"><div className="phoneTop"><span className="smallRings"><i/><i/></span><b><span>Paris</span><em>NOW</em></b><small>PARIS⌄</small></div><div className="phoneBody"><p>PARIS · LOUVRE & OPÉRA</p><h2>Your next<br/><em>great moment</em><br/>starts now.</h2><div className="weather"><span className="weatherIcon" aria-hidden="true">☂</span><div><b>18°</b><small>Light rain</small></div><i/><div><b>65 min</b><small>Available</small></div></div><button>BUILD MY ROUTE →</button><div className="pick"><small>NOW ROUTE · MOSTLY SHELTERED</small><b>Galerie Vivienne → Palais-Royal</b><span>64 min · 0.8 km · starts 7 min away</span></div></div><div className="phoneNav"><b>NOW</b><span>SAVED</span><span>PASS</span></div></div><div className="float one"><small>WEATHER SHIFT</small><b>Rain detected</b><span>Route rebuilt · 2 sec</span></div><div className="float two"><small>TICKET PROTECTION</small><b>Louvre · 4:30 PM</b><span>Protected arrival · armed</span></div></div>
    </section>

    <section className="proof"><p>NOT ANOTHER LIST OF PLACES</p><strong>A decision engine for the city you are actually experiencing.</strong></section>
    <section className="problem" id="how"><div className="problemIntro"><p className="kicker">THE GUIDEBOOK PROBLEM</p><h2>A city never follows<br/><em>the plan you made at home.</em></h2><figure className="editorialImage problemImage"><img src="/images/paris-covered-passage.webp" alt="A rain-washed historic covered passage in Paris at blue hour"/></figure></div><div className="problemGrid">{[["01","The weather turns","NOW changes the kind of experience—not merely the order of the same list."],["02","Your energy changes","Choose low effort, fewer crowds, less walking or a shorter, better route."],["03","A ticket controls the day","NOW protects the reservation, correct entrance and time needed to arrive."],["04","You have an unexpected hour","Start where you really are. No “Start walking” from the wrong side of Paris."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>

    <section className="demo" id="demo"><Heading kicker="PUT NOW TO THE TEST" title="Tell Paris NOW what changed." text="One city. A different decision every time."/><div className="demoGrid"><div className="controls">{Object.entries(scenarios).map(([key,value])=><button className={scenario===key?"active":""} onClick={()=>setScenario(key as keyof typeof scenarios)} key={key}><span>{scenario===key?"●":"○"}</span>{value[0]}</button>)}</div><div className="decision"><div className="decisionTop"><small>BEST MATCH · LIVE EXAMPLE</small><span>96% compatible</span></div><h3>{selected[1]}</h3><div className="route"><i/><div><small>YOUR NOW ROUTE</small><b>{selected[2]}</b><span>{selected[3]}</span></div></div><p><b>Why this route?</b> It protects your time, removes the wrong conditions and preserves one genuinely memorable discovery.</p><a href="#passes">GET THIS KIND OF HELP IN PARIS →</a></div></div></section>

    <section className="features" id="features"><div className="heading dark featuresHeading"><div className="sectionNowMark"><span className="rings"><i/><i/></span><b><span>Paris</span><em>NOW</em></b></div><h2>Built for the moments that ordinary travel apps ignore.</h2><p className="kicker featureKicker">INSIDE YOUR PASS</p></div><figure className="editorialImage featureImage"><img src="/images/paris-hidden-courtyard.webp" alt="A secluded Paris courtyard illuminated at dusk"/></figure><div className="featureGrid">{[["⌁","01 · NOW ROUTES","Minute-by-minute routes","Pre-researched experiences that contract or rebuild around your real time and location."],["☂","02 · WEATHER INTELLIGENCE","Too hot. Too cold. Rain. Snow.","Conditions change the recommendation itself, with shelter and recovery logic."],["◉","03 · TICKET RESCUE","Find a viable ticket—fast","Official ticketing first, qualified alternatives and always a no-ticket Plan B."],["◇","04 · TICKET PROTECTION","Protect what you booked","Your ticket becomes the anchor. NOW contracts the route and guides the right access."],["✦","05 · VELVET PICKS","Rare, discreet, exceptional","NOW can favour places with genuine discovery value, not only famous attractions."],["↗","06 · RECOVERY MODE","When the day goes wrong","A closure, delay or refusal does not need to destroy the day. NOW rebuilds it."]].map(x=><article key={x[1]}><span>{x[0]}</span><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p></article>)}</div></section>

    <section className="activation"><div><p className="kicker">BUY NOW · START LATER</p><h2>Your Pass never<br/><em>starts at checkout.</em></h2><p>Purchase before your trip. Your time begins only when you explicitly choose <b>Activate now</b>—in Paris, when you are ready.</p></div><div className="flow">{[["1","Purchase","Pass status: Not activated"],["2","Arrive in Paris","Open your secure personal link"],["3","Activate","72 hours or 7 days begin"]].map((x,i)=><div className="flowWrap" key={x[0]}><article><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></article>{i<2&&<i>→</i>}</div>)}</div></section>

    <section className="pricing" id="passes"><Heading kicker="CHOOSE YOUR PARIS NOW PASS" title="Less than the price of one wasted hour." text="Tickets, transport and paid attractions are purchased separately."/><div className="priceGrid"><Price title="Paris NOW 72 Hours" price="11" cents=".90" description="Three continuous days from activation." items={["Full NOW decision engine","Weather and energy filters","NOW routes and Velvet Picks","Ticket Rescue and Protection","Activate within 12 months"]} buy={buy}/><Price featured title="Paris NOW 7 Days" price="18" cents=".90" description="Seven continuous days from activation." items={["Everything in the 72-hour Pass","More room for changing plans","Ideal for a full Paris stay","One account, one secure Pass","Activate within 12 months"]} buy={buy}/></div><div id="checkout" className={`checkout ${checkout?"show":""}`}><span>◇</span><div><b>Stripe Checkout will open here.</b><p>Live payment links will be connected after the commercial offer and refund policy are approved. No payment has been taken.</p></div></div><p className="micro">Secure checkout powered by Stripe · Buy now, activate later · English launch edition</p></section>

    <section className="uncovered"><div><p className="kicker">PARIS UNCOVERED PREMIUM OPTION</p><h2><span className="inlineNow"><span>Paris</span><b>NOW</b></span> guides your day.<br/><em>Paris Uncovered takes you beyond the obvious.</em></h2><p><b>Paris Uncovered is a separate permanent digital guide—not included in your Paris NOW Pass.</b> It reveals 25 secret addresses, with exact locations and practical details, for travellers who want to explore beyond their live NOW routes.</p></div><div className="uncoveredSide"><figure className="editorialImage uncoveredImage"><img src="/images/paris-haussmann-evening.webp" alt="A quiet Haussmannian Paris street glowing after rain"/></figure><aside><small>SEPARATE DIGITAL GUIDE · OPTIONAL</small><b>Paris Uncovered</b><span>25 secret addresses · exact locations · mobile-friendly PDF</span><p>Buy once and keep it permanently. Delivered instantly through Etsy.</p><a className="uncoveredCta" href="https://www.etsy.com/listing/4517688727/paris-uncovered-25-secret-addresses" target="_blank" rel="noreferrer">BUY PARIS UNCOVERED →</a></aside></div></section>

    <section className="faq"><div><p className="kicker">QUESTIONS, ANSWERED</p><h2>Before you enter Paris NOW.</h2></div><div>{faqs.map((f,i)=><article className={openFaq===i?"open":""} key={f[0]}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)} aria-expanded={openFaq===i}><b>{f[0]}</b><span>{openFaq===i?"−":"+"}</span></button>{openFaq===i&&<p>{f[1]}</p>}</article>)}</div></section>
    <section className="final"><div className="finalProductMark"><span className="largeRings"><i/><i/></span><b><span>Paris</span><em>NOW</em></b></div><p className="kicker">THE GUIDED APP THAT DIDN’T EXIST—UNTIL NOW</p><h2>Paris, exactly when<br/><em>you need it.</em></h2><a className="button gold" href="#passes">CHOOSE YOUR PASS →</a><small><span>One intelligent travel companion.</span><span>Every city, exactly when you need it.</span></small></section>
    <footer><nav><a href="/terms">Terms</a><a href="/privacy">Privacy</a><a href="/refund-policy">Refund policy</a><a href="/contact">Contact</a></nav><small>© 2026 Velvet Passport. Attraction names and trademarks belong to their respective owners.</small></footer>
  </main>
}

function Heading({kicker,title,text,dark=false}:{kicker:string,title:string,text?:string,dark?:boolean}){return <div className={`heading ${dark?"dark":""}`}><p className="kicker">{kicker}</p><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Price({title,price,cents,description,items,buy,featured=false}:{title:string,price:string,cents:string,description:string,items:string[],buy:()=>void,featured?:boolean}){return <article className={featured?"featured":""}>{featured&&<div className="best">BEST VALUE</div>}<small>{featured?"THE COMPLETE STAY":"SHORT CITY BREAK"}</small><h3>{title}</h3><div className="price"><sup>€</sup>{price}<sup>{cents}</sup></div><p>{description}</p><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><button onClick={buy}>BUY {featured?"7-DAY":"72-HOUR"} PASS →</button></article>}
