import { runForeuse, type ForeuseDocument, type ForeuseResult, type ForeuseTarget } from "./foreuse-core";
import { collectQuebecDirectArchives, directFamilyStats } from "./quebec-direct-archive-collector";
import { collectQuebecCurrentAddressAnchors, QUEBEC_CURRENT_ADDRESS_RULE } from "./quebec-current-address-adapter";
import { evaluateStrongIdentity } from "./foreuse-identity-gate";

const QUEBEC_SOURCE_FAMILIES = [
  {
    id: "ADVITAM",
    label: "BAnQ Advitam",
    domains: ["advitam.banq.qc.ca", "banq.qc.ca", "www2.banq.qc.ca"],
    weight: 10,
    queryHints: ["archives fonds dossier", "plan carte atlas", "nom personne lieu événement", "recherche avancée"],
  },
  {
    id: "VILLE_QUEBEC",
    label: "Ville de Québec archives and heritage",
    domains: ["ville.quebec.qc.ca"],
    weight: 9,
    queryHints: ["archives patrimoine plan rue", "ancien numéro civique", "histoire propriété bâtiment"],
  },
  {
    id: "RPCQ",
    label: "Répertoire du patrimoine culturel du Québec",
    domains: ["patrimoine-culturel.gouv.qc.ca"],
    weight: 9,
    queryHints: ["propriétaire adresse bâtiment", "historique lot rue", "personnage événement"],
  },
  {
    id: "DONNEES_QUEBEC",
    label: "Données Québec",
    domains: ["donneesquebec.ca", "www.donneesquebec.ca"],
    weight: 8,
    queryHints: ["adresses Ville de Québec", "matrice graphique", "empreintes bâtiments", "lieux publics"],
  },
  {
    id: "RQA",
    label: "Référentiel québécois des adresses / current municipal address layer",
    domains: ["mrnf.gouv.qc.ca", "donneesquebec.ca", "www.donneesquebec.ca"],
    weight: 8,
    queryHints: ["Référentiel québécois adresses", "odonyme renvoi", "adresse numéro civique"],
  },
] as const;

export type QuebecForeuseInput = {
  subject: string;
  objective: string;
  location?: string;
  knownFacts?: string[];
  fromYear?: number;
  toYear?: number;
};

function identityText(d: ForeuseDocument) {
  const anyDoc = d as any;
  return [d.title, d.url, anyDoc.description ?? "", d.text ?? ""].filter(Boolean).join("\n");
}

function applyIdentityGate(target: ForeuseTarget, documents: ForeuseDocument[]) {
  const kept: ForeuseDocument[] = [];
  let rejected = 0;
  for (const d of documents) {
    // Exact current-address records are generated by a dedicated municipal dataset adapter.
    // They already passed exact-number + street identity and remain current-anchor-only.
    if (d.query === "DIRECT_CURRENT_ADDRESS" && d.familyId === "RQA") {
      kept.push(d);
      continue;
    }
    const identity = evaluateStrongIdentity(target, identityText(d));
    if (!identity.pass) {
      rejected += 1;
      continue;
    }
    kept.push(d);
  }
  return { kept, rejected };
}

export async function runQuebecArchiveForeuse(input: QuebecForeuseInput): Promise<ForeuseResult> {
  const target: ForeuseTarget = {
    subject: input.subject,
    objective: input.objective,
    location: input.location ?? "Québec, QC, Canada",
    knownFacts: input.knownFacts ?? [],
    dateRange: { from: input.fromYear, to: input.toYear },
    sourceFamilies: QUEBEC_SOURCE_FAMILIES.map((family) => ({ ...family, domains: [...family.domains], queryHints: [...family.queryHints] })),
    seedQueries: [
      `"${input.subject}" Québec archives`,
      `"${input.subject}" Québec plan ancien`,
      `"${input.subject}" Québec lot cadastre propriétaire`,
      `"${input.subject}" Québec annuaire adresse`,
    ],
  };

  const [indexed, rawDirectDocuments, currentAddressDocuments] = await Promise.all([
    runForeuse(target, {
      maxQueries: 16,
      maxSearchHits: 8,
      maxFetches: 14,
      maxMappedLinks: 8,
    }),
    collectQuebecDirectArchives(target),
    collectQuebecCurrentAddressAnchors(target),
  ]);

  const indexedGate = applyIdentityGate(target, indexed.documents);
  const directGate = applyIdentityGate(target, [...rawDirectDocuments, ...currentAddressDocuments]);
  const directDocuments = directGate.kept;

  const mergedByUrl = new Map(indexedGate.kept.map((d) => [d.url, d]));
  for (const d of directDocuments) {
    const old = mergedByUrl.get(d.url);
    if (!old || d.relevance > old.relevance) mergedByUrl.set(d.url, d);
  }
  const documents = [...mergedByUrl.values()].sort((a, b) => b.relevance - a.relevance).slice(0, 30);

  const directStats = directFamilyStats(directDocuments, target);
  const familyStats = target.sourceFamilies.map((family) => {
    const keptIndexed = indexedGate.kept.filter((d) => d.familyId === family.id);
    const original = indexed.familyStats.find((s) => s.familyId === family.id);
    const b = directStats.find((s) => s.familyId === family.id);
    const indexedCumulative = keptIndexed.reduce((sum, d) => sum + d.relevance, 0);
    return {
      familyId: family.id,
      searches: (original?.searches ?? 0) + (b?.searches ?? 0),
      hits: keptIndexed.length + (b?.hits ?? 0),
      fetched: keptIndexed.filter((d) => d.fetched).length + (b?.fetched ?? 0),
      useful: keptIndexed.filter((d) => d.relevance >= 45 || d.evidenceSignals.length >= 2).length + (b?.useful ?? 0),
      cumulativeRelevance: indexedCumulative + (b?.cumulativeRelevance ?? 0),
      yieldScore: Math.max(
        keptIndexed.length ? Math.round(indexedCumulative / keptIndexed.length) : 0,
        b?.yieldScore ?? 0,
      ),
    };
  }).sort((x, y) => y.yieldScore - x.yieldScore);

  return {
    documents,
    familyStats,
    attemptedQueries: [
      ...indexed.attemptedQueries,
      "DIRECT:CKAN",
      "DIRECT:ADVITAM_FAIL_CLOSED_IF_BOT_PROTECTED",
      "DIRECT:VILLE_QUEBEC",
      "DIRECT:RPCQ",
      "DIRECT:RQA_CURRENT_ADDRESS",
    ],
    generatedQueries: indexed.generatedQueries,
    droppedEarly: indexed.droppedEarly + indexedGate.rejected + directGate.rejected,
    rule: `Foreuse Québec v0.4 applies a strong subject-identity gate before ranking evidence. Generic plan/lot/archive vocabulary cannot make a document relevant. Advitam remains fail-closed when bot protection blocks automated catalogue access. ${QUEBEC_CURRENT_ADDRESS_RULE} Direct catalogue hits remain leads until Predator verifies the underlying historical relation.`,
  };
}

export const QUEBEC_ARCHIVE_FOREUSE_RULES = [
  "Strong target identity is a hard gate before document scoring; generic plan/lot/archive keywords never establish relevance.",
  "Prefer direct municipal archives, RPCQ, Données Québec and current-address datasets over generic web discovery for historical micro-location, while keeping every hit as a lead only.",
  "Advitam automated access fails closed when anti-bot protection prevents trustworthy catalogue retrieval; do not fabricate catalogue results.",
  "Current municipal address points corroborate only the current anchor and never prove historical numbering or parcel continuity.",
  "A search, catalogue, API or crawl hit is never parcel continuity proof by itself.",
  "Old civic-number continuity must be demonstrated, not assumed.",
  "A current building may serve as a spatial anchor without being treated as a material witness to an earlier event.",
] as const;
